Adjustments during CR

diff --git a/bin/docker-credential-ecr-custom b/bin/docker-credential-ecr-custom
--- a/bin/docker-credential-ecr-custom
+++ b/bin/docker-credential-ecr-custom
@@ -45,25 +45,28 @@ showUnknownAction() {
 ######################
 
 init() {
-	local registry alias config="$(getServerURLs 2> /dev/null)"
-	printf 'Enter custom registry (ecr.example.com): '
-	read alias
-	printf 'Enter ECR registry (123456789012.dkr.ecr.us-east-1.amazonaws.com): '
-	read registry
-	(echo "$config" ; jq -n "{\"$alias\":\"$registry\"}") | jq -s --tab add > "$ECR_CONFIG"
-	jq . "$ECR_CONFIG"
-}
+  local registry alias config="$(getServerURLs 2> /dev/null)"
 
-initDynamic() {
-	local alias="$1"
+  # Interactive mode
+  if [ -t 0 ]; then
+      printf 'Enter custom registry (ecr.example.com): '
+      read alias
+      printf 'Enter ECR registry (123456789012.dkr.ecr.us-east-1.amazonaws.com): '
+      read registry
+  # Read input in form of alias (e.g. "ecr.example.com") from stdin and get registry from the provided alias dynamically
+  else
+      read alias
 
-  if [ -z "${alias}" ]; then
-    echo "Alias parameter needs to be defined (ecr.example.com), e.g. $BASENAME initDynamic ecr.example.com"
-    exit 1
+      set +e
+      registry="$(curl -LIv "$alias" 2>&1|grep ^Www-Authenticate|grep -oP '(?<=realm=")[^"]*')"
+      set -e
+
+      if [ -z "${registry}" ]; then
+          echo "Cannot get registry from the provided alias: [$alias]. Exiting." >&2
+          exit 1
+      fi
   fi
 
-	local registry="$(curl -LIv "$alias" 2>&1|grep ^Www-Authenticate|grep -oP '(?<=realm=")[^"]*')"
-	config="$(getServerURLs 2> /dev/null)"
 	(echo "$config" ; jq -n "{\"$alias\":\"$registry\"}") | jq -s --tab add > "$ECR_CONFIG"
 	jq . "$ECR_CONFIG"
 }
@@ -97,7 +100,7 @@ main() {
 	test -n "$JQ" || return 1
 	case "$1" in
 		'') showUsage ;;
-		init|initDynamic|get|list|version) "$@" ;;
+		init|get|list|version) "$@" ;;
 		store|erase) ;;
 		*) showUnknownAction "$1" ;;
 	esac
